title: PÄSSION
urls:
  page: http://kikito.github.com/passion
  github: http://github.com/kikito/passion
root_path: /passion
tutorials:
- title: Setup
  dir: setup
  sections:
  - Installing: installing
  - Callbacks: callbacks
- title: OOP & You
  dir: oop-and-you
  sections:
  - "MiddleClass": middleclass
- title: Using passion.Actor
  dir: using-passion-actor
  sections:
  - "Introduction": intro
  - "Update & Draw": update-and-draw
  - "Processing Input": processing-input
  - "Apply & ApplySorted": apply
packages:
- name: passion
- name: passion.graphics
- name: passion.audio
- name: passion.fonts
- name: passion.timers
- name: passion.physics
- name: passion.gui
- name: passion.ai
- name: oop
author:
  name: kikito
  url: http://github.com/kikito

exclude: assets
lsi: false
pygments: true 
auto: true
server: true
safe: false
