title: PÄSSION
urls:
  page: http://kikito.github.com/passion
  github: http://github.com/kikito/passion
root_path: /passion
tutorials:
- title: Setup
  name: setup
  sections:
  - Installing: installing
  - Callbacks: callbacks
- title: OOP & You
  name: oop-and-you
  sections:
  - "Classes & Instances": classes-and-instances
  - "Inheritance": inheritance
  - "Built-in Stuff": built-in-stuff
  - "Mixins": mixins
- title: Using passion.Actor
  name: using-passion-actor
  sections:
  - "Introduction": intro
  - "Update & Draw": update-and-draw
  - "Processing Input": processing-input
  - "Apply & ApplySorted": apply
packages:
- name: passion
- name: passion.graphics
- name: passion.audio
- name: passion.fonts
- name: passion.timers
- name: passion.physics
- name: passion.gui
- name: passion.ai
- name: oop
author:
  name: kikito
  url: http://github.com/kikito

permalink: pretty
exclude: assets
lsi: false
pygments: true 
auto: true
server: true
