title: PÄSSION
url: http://kikito.github.com/passion
github_url: http://github.com/kikito/passion
root_path: /passion
author: kikito
author_url: http://github.com/kikito
links:
  LÖVE: http://www.love2d.org
  PÄSSION github page: http://github.com/kikito/passion
lsi: false
pygments: true
auto: true
server: true
