title: PÄSSION
urls:
  page: http://kikito.github.com/passion
  github: http://github.com/kikito/passion
root_path: /passion
sitemap:
- install:
  - callbacks: callbacks
- passion.Actor:
  - "update & draw": update-and-draw
  - "processing input": processing-input
- passion.graphics:
  -
- passion.audio:
  -
- passion.fonts:
  -
- passion.timers:
  -
- passion.physics:
  -
- passion.gui:
  -
- passion.ai:
  -
- oop:
  -
author:
  name: kikito
  url: http://github.com/kikito
exclude: assets

lsi: false
pygments: true 
auto: true
server: true
